apptension/saas-boilerplate

base.mk
While respecting which shell is configured as the user's default.
=> Run shell with pre-configured environment

tools/version-matrix/public/index.html, tools/version-matrix/src/components/versionMatrix.js, tools/version-matrix/src/styles.js
=> Styles, grey version out if same with env

services/backend/Pipfile, services/backend/Pipfile.lock, services/backend/restauth/settings.py, services/backend/restauth/urls_api.py
The former is deprecated and not working with >= Django 3.0.
=> Replace django-rest-swagger w/ drf-yasg

Makefile, base.mk, docs/app-deployment.md, docs/create-new-env.md, docs/global-infra-deployment.md, docs/services/create-new-serverless-service.md, docs/setup-project.md, infra/cdk/Makefile, infra/functions/Makefile, services/backend/Makefile, services/workers/Makefile
…le which launches shell with AWS env variables
=> Refactor Makefile aws-vault related rules

docs/app-deployment.md, docs/create-new-env.md, docs/global-infra-deployment.md, docs/misc/create-new-serverless-service.md, docs/setup-project.md
Bitbucket-specific issue.
Before the change:
=> Fix docs formatting

infra/cdk/.gitignore, infra/cdk/Makefile, infra/cdk/lib/stacks/env/ci/ciEntrypoint.ts, infra/cdk/lib/stacks/env/ci/functions/trigger-entrypoint/index.js, infra/cdk/lib/stacks/env/ci/functions/trigger-entrypoint/package-lock.json, infra/cdk/lib/stacks/env/ci/functions/trigger-entrypoint/package.json, infra/cdk/package-lock.json
Add lambda function to trigger and pass valid source reference to entrypoint.
=> Fix deploy branches config

.github/pull_request_template.md
Update Github template
Lack of a template
Added a simple template
no
=> feat: Add a default Github pull request template

packages/infra/infra-functions/deployment/triggerEntrypoint.ts, packages/infra/infra-functions/package.json, packages/internal/docs/infra/stacks/docs/stack.ts, pnpm-lock.yaml
Update AWS JS SDK in triggerEntrypoint Lambda
Currently there is v2 which will be deprecated in 2023
Updated to v3
=> refactor: Update AWS JS SDK in triggerEntrypoint Lambda

README.md
Fixes invalid links in README.md
=> chore: Fix README.md links

packages/webapp-libs/webapp-core/src/components/forms/input/input.component.tsx
Migrated component to Radix primitive
=> feat:#174 Migrate to shadcn ui

pnpm-lock.yaml
Fixes issues with the invalid packages causing styles to be broken
=> fix: Application styles broken because of the invalid pnpm-lock.yaml

packages/webapp/src/shared/components/layout/header/header.stories.tsx, packages/webapp/src/shared/components/layout/layout.stories.tsx, packages/webapp/src/shared/components/layout/sidebar/sidebar.stories.tsx, packages/webapp/src/shared/utils/storybook.tsx, packages/webapp/src/tests/utils/rendering.tsx
Fixes broken layout storybooks
=> fix: Layout storybooks

packages/webapp-libs/webapp-core/src/hooks/useTheme/__tests__/useTheme.hook.spec.tsx, packages/webapp-libs/webapp-core/src/hooks/useTheme/index.ts, packages/webapp-libs/webapp-core/src/hooks/useTheme/useTheme.ts, packages/webapp-libs/webapp-core/src/providers/index.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/index.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.context.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.reducer.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.tsx, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.types.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.utils.ts, packages/webapp/.storybook/main.ts, packages/webapp/.storybook/preview.ts, packages/webapp/package.json, packages/webapp/src/app/initApp.tsx, packages/webapp/src/shared/components/layout/header/header.component.tsx, packages/webapp/src/shared/components/layout/sidebar/sidebar.component.tsx, pnpm-lock.yaml, tailwind.workspace-preset.ts
Added a light/dark theme switch that enabled tailwind dark mode.
Currently the state is not saved in any storage. Will add localStorage integration in next PR
=> feat: Add dark/light theme switch

packages/webapp/src/shared/components/layout/layout.component.tsx
=> fix: Sidebar

packages/webapp-libs/webapp-core/src/components/typography/typography.tsx, packages/webapp/src/app/app.component.tsx, packages/webapp/src/routes/admin/__tests__/admin.component.spec.tsx, packages/webapp/src/routes/admin/admin.component.tsx, packages/webapp/src/routes/admin/index.ts
Added some components and more description in admin page
=> feat: Radix UI - Admin page

packages/webapp-libs/webapp-core/src/providers/themeProvider/__tests__/themeProvider.spec.tsx, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.context.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.tsx, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.types.ts, packages/webapp-libs/webapp-core/src/providers/themeProvider/themeProvider.utils.ts
- #229
Added a function for getting theme from local storage and save the theme state in local storage
=> feat: Save theme in local storage

packages/webapp-libs/webapp-core/src/components/pageLayout/__tests__/pageLayout.component.spec.tsx, packages/webapp-libs/webapp-core/src/components/pageLayout/pageLayout.component.tsx, packages/webapp/src/shared/components/auth/changePasswordForm/changePasswordForm.component.tsx, packages/webapp/src/shared/components/auth/editProfileForm/editProfileForm.component.tsx
Fixed gap between content in profile page
=> feat: profile - gap between content

packages/webapp-libs/webapp-core/src/components/buttons/link/link.component.tsx, packages/webapp-libs/webapp-notifications/src/notificationsButton/notificationsButton.component.tsx, packages/webapp/src/shared/components/layout/header/header.component.tsx, packages/webapp/src/shared/components/layout/sidebar/__tests__/sidebar.component.spec.tsx, packages/webapp/src/shared/components/layout/sidebar/sidebar.component.tsx
Better look of the left sidebar + some bits on the navbar
Also added small info about SB (links to the GH and docs) in the bottom part of the sidebar.
Closes #245 #246
=> feat: Polish sidebar look

packages/infra/infra-shared/src/stacks/ci/ciDocs.ts, packages/internal/docs/docusaurus.config.js, packages/internal/docs/project.json, packages/internal/docs/src/css/custom.css
Add Algolia search in docs for the demo env
=> feat: Add Algolia search to docs

packages/webapp-libs/webapp-finances/src/routes/subscriptions/subscriptions.component.tsx, packages/webapp-libs/webapp-finances/src/routes/subscriptions/subscriptions.content.tsx
Adds responsiveness to subscription page
=> Feature/radix UI responsive subscription

packages/webapp-libs/webapp-core/src/theme/color.ts, packages/webapp-libs/webapp-core/src/theme/size.ts
- #230 
- #174 
Removed unused theme variables
=> feat: Removed unused theme variables

packages/webapp/src/shared/components/layout/sidebar/sidebar.component.tsx
=> feat:#271 Rename menu items

packages/internal/docs/sidebars.js
Adds "What is SaaS Boilerplate" menu item as second link
=> feat:#268 Change order of items in docs menu

packages/webapp/src/shared/components/auth/addTwoFactorAuth/addTwoFactorAuth.component.tsx
- #288 
Added max height of content and `overflow: auto;`
=> fix: Scroll on 2FA page - #288

packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/addCrudDemoItem/addCrudDemoItem.component.tsx, packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/editCrudDemoItem/editCrudDemoItem.component.tsx
- #276 
Changed destination route after editing or adding new CRUD item
closes #276
=> fix: Navigation after editing or adding new crud item

packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/addCrudDemoItem/__tests__/addCrudDemoItem.component.spec.tsx, packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/addCrudDemoItem/addCrudDemoItem.component.tsx, packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/crudDemoItemList/crudDemoItemListItem/__tests__/crudDemoItemListItem.component.spec.tsx, packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/crudDemoItemList/crudDemoItemListItem/crudDemoItemListItem.component.tsx
Adds toast message when CRUD item is deleted.
=> fix:#277 Add message while deleting item

packages/webapp-libs/webapp-api-client/package.json, packages/webapp/package.json, pnpm-lock.yaml
Fixes #297
Add missing `graphql` dependency causing errors on starting webapp.
=> fix: #297 Fix missing graphql dependency issue

packages/internal/docs/docusaurus.config.js
Add Google Tag Manager tracking id to the docs.
=> feat: Add Gtag tracking to the docs

packages/webapp-libs/webapp-finances/src/components/stripe/stripePaymentMethodSelector/stripePaymentMethodSelector.component.tsx, packages/webapp-libs/webapp-finances/src/routes/cancelSubscription/cancelSubscription.component.tsx
Fixes lack of space in cancel subscription page and adds skeleton n edit payment method page
=> fix: lack of space in payments

README.md
Added shields to the README.md with the Twitter and Discord + information about discord server to the contribute section
=> feat: Community links

packages/internal/docs/docusaurus.config.js
Replaces invalid Gtag configuration in the docs with the correct GTM config.
=> fix: Replace Gtag with GTM in docs

packages/webapp/public/manifest.json
=> fix: Fix invalid links in webapp manifest.json

packages/internal/docs/src/css/custom.css
Fixes invalid link color when `<a>` is not inside `<p>` element.
=> fix: [docs] Fix invalid link color

.versionrc.js
Added all missing `package.json` files to the version bump script.
=> fix: Fix invalid version bump skipping some package.json files

packages/webapp/src/shared/components/layout/sidebar/sidebar.component.tsx
Changed how BP logo is changing with theme
=> fix: re render sidebar on menu change

README.md, packages/internal/docs/docs/getting-started/run-project/_install-deps.mdx, packages/internal/docs/docs/getting-started/run-project/_requirements.mdx, packages/internal/docs/docs/getting-started/run-project/_start-app.mdx, packages/internal/docs/docs/shared/partials/_wsl_notice.mdx
Added information about WSL to the README.md and documentation. Updated requirements.
=> docs: #358 Add WSL to the Windows requirements + update them

packages/workers/package.json, packages/workers/serverless.yml, pnpm-lock.yaml
Bump python runtime on workers lambda functions: Fixes https://github.com/apptension/saas-boilerplate/issues/362
=> fix: #362 Update python runtime version in workers to 3.11

packages/backend/apps/finances/management/commands/init_subscriptions.py, packages/backend/apps/finances/signals.py, packages/backend/apps/users/management/commands/init_customers_plans.py, packages/backend/apps/users/tests/factories.py, packages/backend/apps/users/tests/fixtures.py, packages/backend/apps/users/tests/test_commands.py, packages/backend/apps/users/tests/test_signals.py, packages/backend/scripts/run_local.sh, packages/backend/scripts/run_migrations.sh, packages/backend/sonar-project.properties
Fixes #328 
Change behaviour of post_save signal on User model
Currently mentioned signal is making request to Stripe API creating customer and subscription schedule.
Which leads to error on sign up, when Stripe keys are not provided
Post signal skips calls which are raising AuthenticationError
New command is added to run_local.sh script, which will perform same action for users, who has no attached stripe customer and subscription schedule
=> fix: #328 sign-up-returns-validation-error-on-fresh-installation-without-env-variables

packages/internal/docs/docs/api-reference/backend/commands.mdx, packages/internal/docs/docs/api-reference/tools/commands.mdx, packages/internal/docs/docs/api-reference/webapp-api-client/commands.mdx, packages/internal/docs/docs/api-reference/webapp-emails/commands.mdx, packages/internal/docs/docs/api-reference/webapp/commands.mdx, packages/internal/docs/docs/working-with-sb/dev-tools/version-matrix.mdx, packages/internal/docs/docs/working-with-sb/graphql/web-app/update-schema.mdx, packages/internal/docs/docs/working-with-sb/payments/one-time-payment-form.mdx, packages/internal/docs/docs/working-with-sb/project-structure/create-web-lib.mdx
Prefix every `nx` call with `pnpm` in the docs
=> docs: Prefix every `nx` call with `pnpm` in the docs

packages/infra/infra-shared/package.json, packages/infra/infra-shared/src/bootstrap.ts, packages/infra/infra-shared/src/main.ts, packages/internal/core/custom-task-runner.js
Bug fix
Closes #356 
Freshly created project cannot be pushed to AWS due to a deadlock scenario.
Deadlock is removed
No
=> fix: Fix deadlock preventing infra bootstrapping

packages/internal/cli/src/commands/ci/create-credentials.ts, packages/internal/cli/src/config/telemetry.ts
- 
Add OS attributes to CLI telemetry
=> feat: Add OS attributes to CLI telemetry

.github/workflows/actions/setup/action.yml, .github/workflows/backend.yml, .github/workflows/docs.yml, .github/workflows/infra.yml, .github/workflows/status-dashboard.yml, .github/workflows/tools.yml, .github/workflows/webapp.yml, .github/workflows/workers.yml, README.md, packages/infra/infra-functions/serverless.yml, packages/internal/cli/package.json, packages/internal/docs/docs/getting-started/run-project/_requirements.mdx, packages/internal/local-ws-server/Dockerfile
=> feat: #391 Update minimum node.js version to 18

packages/internal/docs/docs/shared/partials/env-vars/_workers_optional.mdx
Fix incorrect description of the Contentful environment variables for workers
=> docs: Fix workers contentful env documentation

packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx, packages/internal/docs/docs/aws/troubleshooting.mdx, packages/internal/docs/sidebars.js
docs update
Missing documentaiton for variable
Not missing documentation for variable 
no
=> docs: Add missing documentation for SB_CERTIFICATE_DOMAIN variable

packages/internal/docs/docs/working-with-sb/guides/web-app/create-react-component.mdx
Fixes invalid import path in the docs article.
=> docs: Fix invalid path to file in create react component docs article

packages/internal/local-ws-server/scripts/run.sh, packages/workers/.pdm-python, packages/workers/.pdm.toml, packages/workers/Dockerfile, packages/workers/pdm.lock, packages/workers/pdm.toml, packages/workers/pyproject.toml, packages/workers/workers.conf.yml
Fixes #433
Fixes errors from AWS lambda incorrectly configured python environment.
Lambda is trying to use python 3.9 instead of 3.11
Lambdas are correctly using correct python 3.11
=> Fix: Websocket connection error on AWS env

packages/internal/docs/docs/shared/partials/env-vars/_webapp.mdx
Fixes #445 
Missing env var for the webapp in the docs.
=> docs: #445 Add missing VITE_SUBSCRIPTIONS_URL env var to the docs

packages/internal/cli/src/lib/secretsEditor.ts
=> chore: Fix secretsEditor.ts file styling

packages/infra/infra-shared/src/stacks/ci/ciEntrypoint.ts, packages/infra/infra-shared/src/stacks/ci/ciPipeline.ts
Fixes #196 
Use event-based mechanism instead of polling for change detection in CodePipeline
Current pipeline uses polling mechanism which is not recommender anymore.
No
=> feat: #196 Migrate polling AWS CodePipeline to use event-based change detection

packages/internal/docs/.eslintrc.json, packages/internal/docs/docs/index.mdx, packages/internal/docs/docs/shared/components/DisplayLocalUseInfo.component.tsx, packages/internal/docs/docs/shared/partials/_local-use-info.mdx, packages/internal/docs/docusaurus.config.js
Added info that will be displayed in the publicly available docs and will inform developers that this docs are related to the latest release and to run local version.
=> docs: Add instructions to run local documentation

packages/internal/docs/docs/aws/deploy-to-aws/configure-aws-credentials.mdx, packages/internal/docs/docs/aws/deploy-to-aws/index.mdx, packages/internal/docs/docs/shared/partials/_freash-aws-account-info.mdx
Related to #453
Added information to the docs about issues on fresh AWS accounts:
- SES in sandbox mode by default
- CodeBuild concurrent build limits
There is no information about known issues on fresh AWS accounts. This can lead developers that are new to AWS and SB to have problems with the deployment.
=> docs: Add information to the docs about issues on fresh AWS accounts

packages/backend/package.json, packages/backend/project.json, packages/infra/infra-core/package.json, packages/infra/infra-core/src/lib/env-config.ts, packages/infra/infra-functions/package.json, packages/infra/infra-functions/project.json, packages/infra/infra-shared/package.json, packages/infra/infra-shared/project.json, packages/internal/cli/src/commands/infra/bootstrap.ts, packages/internal/docs/docs/api-reference/backend/commands.mdx, packages/internal/docs/package.json, packages/internal/docs/project.json, packages/internal/status-dashboard/package.json, packages/internal/status-dashboard/project.json, packages/webapp/package.json, packages/webapp/project.json
Move scripts from package.json to project.json to avoid issues with env variables passing
=> fix: Move scripts from package.json to project.json

packages/backend/apps/multitenancy/admin.py
Adding django admin panel for tenants
=> feat: multi tenancy admin panel

packages/webapp-libs/webapp-emails/src/templates/tenantInvitation/tenantInvitation.component.tsx
Set the correct URL and copy in the invitation email.
Closes #465
=> fix: Fix invalid URL in tenant invitation email

packages/webapp-libs/webapp-tenants/src/components/routes/tenantAuthRoute/__tests__/tenantAuthRoute.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/routes/tenantAuthRoute/index.ts, packages/webapp-libs/webapp-tenants/src/components/routes/tenantAuthRoute/tenantAuthRoute.component.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/__tests__/tenantSwitch.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/tenantSwitch.component.tsx, packages/webapp-libs/webapp-tenants/src/hooks/index.ts, packages/webapp-libs/webapp-tenants/src/hooks/useCurrentTenantRole/__tests__/useCurrentTenantRole.hook.spec.tsx, packages/webapp-libs/webapp-tenants/src/hooks/useCurrentTenantRole/index.ts, packages/webapp-libs/webapp-tenants/src/hooks/useCurrentTenantRole/useCurrentTenantRole.hook.ts, packages/webapp-libs/webapp-tenants/src/hooks/useTenantRoleAccessCheck/useTenantRoleAccessCheck.hook.ts, packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.component.tsx, packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.storage.ts, packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.types.ts, packages/webapp/src/app/app.component.tsx
Review after #520 
Closes #466 
Added TenantAuthRoute component along with tenant role checks in the app.
=> feat: Add TenantAuthRoute component and tenant role checks

packages/backend/apps/finances/schema.py, packages/backend/apps/finances/tests/test_schema.py
Add tenantId as a parameter to queries resolvers 
It was missing
=> Fix tenant related queries and tests for finances app

packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/__tests__/tenantSwitch.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/tenantSwitch.component.tsx
Fix test coverage for webapp-tenants
=> fix: test coverage of webapp-tenants

packages/webapp-libs/webapp-tenants/src/routes/tenantSettings/tenantMembers/__tests__/tenantMembers.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/routes/tenantSettings/tenantMembers/tenantMembers.component.tsx
Add additional info in the personal settings' members tab
=> feat: add additional info in the personal settings' members tab

packages/webapp-libs/webapp-tenants/src/components/tenantDangerZone/__tests__/tenantDangerZone.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantDeleteAlert/__tests__/tenantDeleteAlert.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantDeleteAlert/tenantDeleteAlert.component.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/__tests__/tenantSwitch.component.spec.tsx, packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/tenantSwitch.component.tsx, packages/webapp-libs/webapp-tenants/src/routes/tenantSettings/tenantMembers/tenantMembers.component.tsx
=> fix: Multi-tenancy: coherent organization naming

package.json, pnpm-lock.yaml
Update `@sentry/react` to new major version. Some changes were anticipated, however none were needed.
=> deps: Update @sentry/react

packages/internal/core/project.json
Fix for volume not being recreated for the 2nd time [Issue](https://github.com/apptension/saas-boilerplate/issues/403)
=> fix: docker volume recreate

packages/webapp-libs/webapp-api-client/src/hooks/usePaginatedQuery/__tests__/usePaginatedQuery.hook.spec.tsx, packages/webapp-libs/webapp-api-client/src/hooks/usePaginatedQuery/usePaginatedQuery.hook.ts, packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/crudDemoItemList/__tests__/crudDemoItemList.component.spec.tsx
The previous page indicator is properly set. Set the first page on unmount of the list.
[Issue](https://github.com/apptension/saas-boilerplate/issues/443)
=> fix: crud pagination

packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.component.tsx, packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.utils.ts
I had a problem understanding the code with those `lets` at the first glance. (`CurrentTenantProvider`)
I have created utils. 
Feel free to cancel the PR if you think the change is redundant. @mkleszcz
=> feat: refactor of current tenant provider

packages/webapp/src/app/app.component.tsx, packages/webapp/src/app/config/routes.ts
Removed unnecessary repetitions of `path` from `app.component`.
=> feat: simplify routing component

packages/backend/apps/users/models.py, packages/webapp-libs/webapp-tenants/src/components/tenantInvitationForm/tenantInvitationForm.component.tsx, packages/webapp-libs/webapp-tenants/src/routes/tenantSettings/tenantMembers/tenantMembers.component.tsx, packages/workers/userauth/models.py
=> fix: #601 Fix copy inconsistency

packages/internal/docs/docs/shared/partials/env-vars/_webapp_optional.mdx
=> docs: Fix incorrectly formatted table in the docs

packages/internal/docs/docs/working-with-sb/graphql/web-app/update-schema.mdx
=> fix: Fix invalid docs formatting

packages/webapp-libs/webapp-core/src/toast/toastProvider/toastProvider.reducer.ts
Fix typo in the error message.
=> chore: Fix typo

bitbucket-pipelines.yml
Fixed Bitbucket pipelines configuration.
Currently pipelines are failing because of the memory assigned in the wrong way.
All steps of the pipeline should pass.
=> fix: Bitbucket pipelines configuration

packages/webapp/src/routes/home/home.component.tsx
Unify subscription links in the sidebar and home page
=> fix: #600 Unify subscriptions links

packages/backend/apps/demo/models.py
Bug fix
When removing file from documents it still exists in s3 bucket.
I added behavior to remove file from s3 bucket.
Nope
=> fix: #597 remove file from s3 after deleting from db

packages/backend/.env.shared, packages/backend/apps/integrations/openai/client.py, packages/backend/apps/integrations/tests/test_clients.py, packages/backend/config/settings.py
Bug fix
Bug, because currently used model is depracated.
Changed default model to gpt-3.5-turbo-instruct which is fine currently. Also add parameter for model, to allow users to decide what model they want to use.
Nope
=> fix: #593 change openAI model and parametrize it
