- services/backend/common/__init__.py
- services/backend/common/emails.py
- services/backend/common/tasks.py
- services/backend/restauth/settings.py
Previously, every task was sent as AWS event, which caused error for
local environment setup.
Now, there is possibility to set different handler, e.g. one that prints
every task to stdout and nothing more.
> Allow to configure task handler

- services/backend/restauth/serializers.py
User's id is later required in password reset confirmation view.
> Add user to password reset notification

- services/workers/emails/handlers.py
SendEmail lambda function has different event structure on localstack and dev, which makes it crash
* Localstack
```
[INFO]	2020-08-03T08:38:37.1Z	f8b3f44c-221f-12fb-16ec-8c3153aabd5b	{
"type": "WelcomeEmail",
"to": "fwolwowicz@example4.com",
"name": "Filip",
}
```
* Dev
```
[INFO]	2020-07-31T14:17:29.903Z	948a62b7-b762-446b-b1b0-8fd75b138e02	
{
"version": "0",
"id": "eff45b72-a0f1-8571-5c69-d2cc813feb5f",
"detail-type": "WelcomeEmail",
"source": "backend.email",
"account": "946438046401",
"time": "2020-07-31T14:17:28Z",
"region": "eu-west-1",
"resources": [],
"detail": {
"type": "WelcomeEmail",
"to": "fwolwowicz@example4.com",
"name": "Filip"
}
}
```
> Unpack send-email event details

- .github/workflows/main.yml
* **What kind of change does this PR introduce?**
Bug fix
* **What is the current behavior?**
Pull requests that do not have access to github secrets (like dependabot) fail build because of CodeCommit syn job.
* **What is the new behavior ?**
CodeCommit job does not run when CODE_COMMIT_REPO env var is not defined.
* **Does this PR introduce a breaking change?**
no
> fix: Add condition that pushes code to CodeCommit only CODE_COMMIT_REPO secret is defined

- packages/internal/core/project.json
- packages/internal/ssm-editor/project.json
Closes #177 
`make up` fails if `.env` file does not exist in packages/e2e-tests
`.env.` file is automatically created when `make up` is run.
no
Make sure you run `nx reset` to remove `nx` cache before you run `make up` if you encountered the error
> fix: Add command that runs all setup targets to make sure all .env files are created

- packages/infra/infra-shared/src/patterns/webAppCloudFrontDistribution.ts
- packages/infra/infra-shared/src/stacks/usEastResources/authLambda/index.js
- packages/infra/infra-shared/src/stacks/usEastResources/stack.ts
- packages/internal/docs/infra/stacks/docs/stack.ts
Migrate from CloudFrontWebDistribution to the newer Distribution construct, fix WepAppStack deployment
Fixes #181 
Fresh deployment of WebAppStack fails because of the new S3 default policy.
Issue with the fresh installation is now gone.
> fix: #181 Migrate from CloudFrontWebDistribution to the newer Distribution

- packages/backend/scripts/run_local.sh
closes #224 
Stripe's subscriptions are initialised without Products and Prices sync first, which causes to create duplicates with a fresh database instance.
Products and Prices are synced before running `init_subscriptions` command, which prevents creating duplicates with a fresh db instance and subscription plans already present in the stripe account.
> fix: Sync stripe's Product and Price before initialising subscriptions

- .github/workflows/backend.yml
- .github/workflows/docs.yml
- .github/workflows/workers.yml
- docker-compose.ci.yml
- packages/backend/Dockerfile
- packages/backend/scripts/build.sh
- packages/e2e-tests/Dockerfile
- packages/infra/infra-core/src/lib/env-config.ts
- packages/infra/infra-core/src/lib/patterns/serviceCiConfig.ts
- packages/infra/infra-shared/src/stacks/ci/ciBackend.ts
- packages/infra/infra-shared/src/stacks/ci/ciComponents.ts
- packages/infra/infra-shared/src/stacks/ci/ciDocs.ts
- packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
- packages/infra/infra-shared/src/stacks/ci/ciUploadVersion.ts
- packages/infra/infra-shared/src/stacks/ci/ciWebApp.ts
- packages/infra/infra-shared/src/stacks/ci/e2eTests.ts
- packages/infra/infra-shared/src/stacks/global/resources/globalECR.ts
- packages/workers/Dockerfile
closes #204 
Inside CodePipeline, sometimes the deployment fails because of dockerhub 429 Too Many Requests error.
The official images (ex. python, cypress) are downloaded from public AWS ECR repo and pulled from cache subsequently.
> fix: Use ECR public images with Pull-Through-Cache inside AWS CodePipeline

- packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
- packages/infra/infra-shared/src/stacks/ci/e2eTests.ts
- packages/internal/docs/docs/api-reference/env-files.mdx
- packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
- packages/internal/docs/docs/working-with-sb/dev-tools/version-matrix.mdx
- packages/internal/status-dashboard/package.json
- packages/internal/tools/project.json
closes #206 
Tools and status dashboard scripts are trying to reference removed `.env.tools`
Required env variables have been added to AWS SSM Parameter store and are retrieved via chamber.
> fix: Reference tools' env variables via AWS Parameter Store

- packages/webapp-libs/webapp-contentful/src/routes/demoItems/demoItems.component.tsx
- #274 
Added `useEffect` that refetch data in contentfull item list page
closes #274
> fix: Refresh contentful item list page

- .versionrc.js
Closes #309
Main `package.json` is skipped from version bump when on `standard-version` call
It's updated as should ;)
> fix: #309 Fix invalid version bump skipping main package.json file

- packages/backend/apps/users/views.py
- packages/backend/pdm.lock
- packages/backend/pyproject.toml
Bug fix
Build of backend's docker image throws an error `"AttributeError: cython_sources" with Cython 3.0.0a10`
Updated an offending library to remove the error.
Closes #340 
no
> fix: Upgrade pyyaml to version 6.0.1 to avoid cython_sources installation issue

- packages/internal/core/stage-env-validator.js
Bugfix
If those variables are not set in AWS Parameter Store, no default value is provided.
Populate base images env variables with defaults.
> fix: Add docker base images with defaults to stage-env-validator

- packages/backend/infra/stacks/api/stack.ts
Increases memory limit for the backend ECS task
There is an issue with the our of memory for the task causing it to constantly restart and create new task on ECS. Additionally there might be an issue with the deployment which gets an timeout error.
> fix: Increase memory limit for backend ECS task

- packages/backend/Dockerfile
- packages/backend/Makefile
- packages/backend/config/settings.py
- packages/backend/gunicorn.py
- packages/backend/infra/stacks/api/stack.ts
- packages/backend/pdm.lock
- packages/backend/project.json
- packages/backend/pyproject.toml
- packages/backend/scripts/execute_remote.sh
- packages/backend/scripts/run.sh
- packages/infra/infra-core/src/lib/patterns/applicationMultipleTargetGroupsFargateService.ts
- packages/infra/infra-core/src/lib/patterns/applicationMultipleTargetGroupsFargateServiceBase.ts
Bug fix
During deployment, Backend API service is never able to register a new Task Definition, because it never passes health checks.
Seems that we're running too many workers (2*cpu count + 1) on too small of a task (512 vCPU) and they just don't have enough CPU to work with.
We limit number of workers when `DEBUG` is on. I think it's a better approach than increasing the size of the task to save costs. 
I also moved gunicorn dependency to pytoml file.
no
> fix: Fix API deployment issues on a small ECS task

- packages/webapp-libs/webapp-contentful/scripts/download-graphql-schema.sh
if the contentful env vars are not set
This is an improvement: it allows the developers to run `nx run webapp:graphql:download-schema` without specifying the environment variables for Contentful (usually such an integration will come later in the development process), and also some developers might not use Contentful at all.
Currently,  `nx run webapp:graphql:download-schema` cannot be run without Contentful environment variables
No braking change introduced.
I am not sure what kind of tests could be done for such a change.
I do not think this change requires doc update.
Please advise.
> fix: allow running nx run webapp:graphql:download-schema

- packages/internal/docs/docs/working-with-sb/graphql/web-app/form-with-mutation.mdx
This is a fix
the documentation was not correctly describing that the `setApolloGraphQLResponseErrors` method is a method of the `form` object. A new user to graphql (like me) would be wondering about how to use it.
Now the doc correctly describes how to use this `setApolloGraphQLResponseErrors` method
No braking chnage
> fix: documentation error for form-with-mutation.mdx

- .github/workflows/backend.yml
- .github/workflows/docs.yml
- .github/workflows/infra.yml
- .github/workflows/status-dashboard.yml
- .github/workflows/tools.yml
- .github/workflows/webapp.yml
- .github/workflows/workers.yml
- Makefile.base.mk
- bitbucket-pipelines.yml
Bug fix
Closes #341 
Some of the rules in Makefile.base.mk do not use `pnpm` to run `nx`, which creates a global dependency on `nx`. 
We use `pnpm nx` to run `nx` scripts which uses local installation in `node_modules/.bin`
no
I also changed some hardcoded `node_modules/.bin/nx` paths to `pnpm nx`
> fix: Use local nx installation by running it through pnpm in all scripts and make rules

- packages/internal/docs/docs/aws/index.mdx
- packages/internal/docs/docs/getting-started/index.mdx
- packages/internal/docs/docs/getting-started/run-project/run-existing-project.mdx
- packages/internal/docs/docs/getting-started/run-project/run-new-project.mdx
- packages/internal/docs/docs/introduction/index.mdx
- packages/internal/docs/docs/working-with-sb/index.mdx
- packages/internal/docs/sidebars.js
Adjusted documentation next links:
- Removed links from some autogenerated index pages
- Changed next links for `Getting started` pages
> docs: Adjust documentation next links

- packages/internal/docs/docs/api-reference/webapp/commands.mdx
- packages/webapp-libs/webapp-contentful/src/routes/demoItems/demoItems.component.tsx
- packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/addCrudDemoItem/addCrudDemoItem.component.tsx
- packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/crudDemoItemList/crudDemoItemListItem/crudDemoItemListItem.component.tsx
- packages/webapp-libs/webapp-crud-demo/src/routes/crudDemoItem/editCrudDemoItem/editCrudDemoItem.component.tsx
- packages/webapp-libs/webapp-documents/src/routes/documents/documents.component.tsx
- packages/webapp/package.json
Fixes #338 
It generates the file in the incorrect place (in the `webapp` instead of the `webapp-core`) and with incorrect content (it does not scan `webapp-libs` packages for the copy)
It generates the file with the correct contents in the correct place
> Fix: `extract-intl` script not working as expected

- README.md
Link all used libs in README.md
> docs: Link all used libs in README.md

- packages/internal/cli/src/config/env.ts
Bug fix
Closes #397 
Looks like `git describe` fails when no tags are present in repository or head is in detached state.
Added a try catch around the git describe code and set version `0.0.1` as default.
no
> fix: Set version to 0.0.1 when git is unable to determine a version in case no tags exist in repository

- packages/internal/cli/src/baseCommand.ts
Removes CLI command args from telemetry data
> fix: Remove command args from telemetry

- packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
- packages/internal/cli/src/commands/emails/build.ts
- packages/internal/cli/src/commands/emails/secrets.ts
- packages/internal/cli/src/commands/workers/deploy.ts
- packages/workers/package.json
- packages/workers/project.json
- pnpm-lock.yaml
bug fix
Emails artifact is not built when `saas workers build` or `saas workers deploy` is run.
Added webapp-emails as a dependency to `workers` and `webapp-emails:build` as a dependency for both `build` and `deploy` targets in workers package.
Changed SSM service to workers during emails build, instead of webapp. Makes much more sense.
yes. when building emails, SSM variables will be pulled from workers (use `saas workers secrets` to set them) instead of webapp.
> fix: Enforce emails artifact build before workers build / deploy is executed to make sure emails/renderer/index.umd.js is present

- packages/internal/cli/src/commands/docs/build.ts
Fixes invalid environment loaded when `pnpm saas docs build` called causing the documentation to build without search bar and analytics.
Docs doesn't build with all features.
Docs will be built with all desired features.
> fix: Invalid build environment for the docs

- packages/internal/cli/src/commands/up.ts
feature
closes #417 
for `saas up` CLI command, web app dev server is immediately started after backend container is started
for `saas up` CLI command,web app dev server is started only after backend API endpoint returns a valid HTTP code.
no
> feat: Add a waiting mechanism to `saas up` CLI command to wait for backend to start before starting web app dev server

- packages/backend/infra/stacks/api/stack.ts
- packages/infra/infra-core/src/lib/env-config.ts
bug fix
closes #415 
User will get a very ambiguous error when one of domains is not set.
We display a clear error when user does not define `SB_DOMAIN_API` variable but also other `SB_DOMAIN_*` vars are mode optional for the API stack.
no
> fix: Prevent API stack from throwing error during deployment when user does not define all domains.

- CONTRIBUTING.md
- packages/internal/docs/docs/working-with-sb/guides/backend/backend-model.mdx
Added info to fix the invalid django app name in the create new django model guide.
`pnpm saas backend makemigrations` command throws an error in the [guide](https://docs.demo.saas.apptoku.com/working-with-sb/guides/backend/backend-model) because after generating new django app, it has got invalid name in the `apps.py` file.
Guide should provide all the instructions to go through it without any issues.
> docs: Invalid django app name

- packages/backend/project.json
- packages/infra/infra-shared/package.json
- packages/internal/cli/src/config/init.ts
- packages/internal/cli/src/lib/secretsEditor.ts
- packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
- packages/internal/docs/docs/shared/partials/env-vars/_backend.mdx
- packages/internal/docs/docs/shared/partials/env-vars/_webapp.mdx
- packages/internal/docs/docs/shared/partials/env-vars/_webapp_optional.mdx
- packages/internal/docs/docs/shared/partials/env-vars/_workers.mdx
- packages/workers/workers.conf.yml
Fixes: #425
Related to: #426
This changes fixes problem with the last commands of the AWS deploy instructions (docs: https://docs.demo.saas.apptoku.com/aws/deploy-to-aws/run-deployment-commands).
It fixes two issues:
1. Invalid `ENV_STAGE` value in the workers deployment that leads to wrong stage argument in the sls deployment. This is caused by picking docker-compose.local.yml file instead of docker-compose.ci.yml.
2. Stuck `ApiStack` during deployment caused by invalid order of the migrations during deployment (migrations after `ApiStack` deploy).
When `pnpm saas ...` is called in the non `local` env scope (set by `pnpm saas aws set-env {ENV}` the right docker-compose.yml file is picked.
When `pnpm saas deploy` is called, there is the right order of backend migrations and API stack …
> Fix: App deployment from local repository

- packages/backend/Dockerfile
Fixes missing execute rights in the docker container that is missing on Windows
Related to: #426 
As per message on Discord: https://discord.com/channels/1122849885335597088/1169777357125582958/1174626942964748409
It will fix the issue on Windows machines
> fix: Add chmod +x for the runtime scripts in backend Dockerfile

- README.md
- packages/internal/docs/docs/getting-started/run-project/run-new-project.mdx
Added info about `PATH` parameter to the init script in docs.
There is no information about the parameter and some users strugle to initialize the project in the not empty directory.
There is a clear information that user need to initialize project in empty directory
No
> docs: Add PATH parameter to the init script description in docs

- packages/backend/Dockerfile
Fixes #454 
Freeze of awscli version in Dockerfile of backend application.
Failing with `ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils'` during container startup.
Backend application is starting up without errors.
No
> fix: #454 Freeze awscli version to 1.32.24 in backend Dockerfile

- .husky/pre-commit
Fixes #446
`@nx/enforce-module-boundaries` eslint plugin throws an error on initial commit when there is no NX graph generated.
This issue won't occur when called any NX command before commit.
Added a check in the precommit code that is looking for `.nx` directory and if doesn't exists calls `pnpm nx show projects 1> /dev/null`
No
> fix: Precommit hook failing on initial commit without NX graph generated

- package.json
- packages/backend/scripts/build.js
- packages/internal/cli/src/config/env.ts
- packages/internal/cli/src/config/init.ts
- packages/workers/Dockerfile
- patches/nx@17.1.3.patch
- pnpm-lock.yaml
Bug fix
Closes #475 
NX loads .env files from webapp and backend packages when running CLI commands. Some of variables are interfering with the execution of the script. They should only be loaded by Docker or Vite during runtime of apps, not scripts.
Patched `nx` package to prevent this behaviour with an ENV variable set within CLI.
Not a breaking change but if someone used .env files in a wrong way that could cause conflict.
> fix: Prevent NX from loading .env files when running CLI scripts.

- packages/infra/infra-core/src/lib/env-config.ts
- packages/infra/infra-core/src/lib/patterns/serviceCiConfig.ts
- packages/infra/infra-shared/src/stacks/ci/ciBackend.ts
- packages/infra/infra-shared/src/stacks/ci/ciComponents.ts
- packages/infra/infra-shared/src/stacks/ci/ciDocs.ts
- packages/infra/infra-shared/src/stacks/ci/ciPipeline.ts
- packages/infra/infra-shared/src/stacks/ci/ciServerless.ts
- packages/infra/infra-shared/src/stacks/ci/ciUploadVersion.ts
- packages/infra/infra-shared/src/stacks/ci/ciWebApp.ts
- packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
Fixes #479 
Added a `simple` CI mode that will reorder AWS CodeBuild inside AWS CodePipeline CI stages. It will change the behavior of the CI to run in non-concurrent mode, which is needed for fresh AWS accounts.
There are some issues on the fresh AWS accounts because of the concurrent AWS CodeBuild limits.
This setting allow to workaround the problem.
No. By default the CI will run in parallel.
> feat: Introduce CI mode

- .dockerignore
- packages/backend/.dockerignore
- packages/internal/cli/src/commands/up.ts
- packages/workers/.dockerignore
- packages/workers/Dockerfile
Fixes #458
This PR includes fixes for 3 different issues that was discovered during debugging #458:
- node_modules from the host where shared to the docker containers causing issues on Windows machines
- issue with the invalid environment variables (PATH) into workers process causing to use python3.9 instead of python3.11. This issue caused the missing module errors in the workers container.
- missing `pnpm saas emails build` command when starting the local environment by `pnpm saas up`
All of the issues above exists.
- Fixes incorrect paths in the .dockerignore files
- Removed NX from workers CMD image
- Added `pnpm saas emails build` call into `pnpm saas up`
Nope.
> fix: Workers docker issues

- packages/backend/sonar-project.properties
Fixes #485 
This PR changing the configuration of backend SonarCloud coverage check. After merge SonarCloud check will ignore files in tests subdirectories as well as files in tests directory.
SonarCloud check is ignoring only files in main test directory. It is calculating coverage with files in subdirectories.
Ignoring files in subdirectories too.
No
> fix: change SonarCloud exclusions configuration

- packages/internal/docs/project.json
Fixes #449 
There is an issue when someone will try to start the docs before the main application. There is a missing docker volume so docs won't start.
Running create docker volume script before docs start. It will ensure that it's created before running docs even before app startup.
No.
> fix: #449 Ensure that docker volume is created when running docs locally

- packages/backend/apps/multitenancy/schema.py
- packages/backend/apps/multitenancy/tests/test_schema.py
Making all tenants query public
It's not public
Responding with empty table when not logged user is querying about allTenants
Nope
> feat: multi tenancy public all tenants query

- packages/webapp-libs/webapp-api-client/src/tests/mocks/server/handlers/graphql.ts
- packages/webapp-libs/webapp-api-client/src/tests/mocks/server/handlers/index.ts
Removes warning in tests from MSW unhandled requests
Latest updates with websockets introduced warnings in tests from MSW that logs unhandled requests. New WS client sends GET requests to the mocked server (default mocked is not working in this case) and MSW doesn't have it.
Enabled MSW handlers for `/api/graphql` routes.
Nope.
> fix: Remove warning in tests from MSW unhandled requests

- packages/backend/.env.shared
Hi there,
I noticed that the AWS_ENDPOINT_URL=http://localstack:4566 line in the packages/backend/.env.shared file is no longer needed, as this flag is now being passed by docker-compose.local.yml. This line is causing the migration job to fail when running pnpm saas deploy as it can't resolve localstack.
To fix this issue, I have removed the AWS_ENDPOINT_URL=http://localstack:4566 line from the packages/backend/.env.shared file. This should resolve the issue and allow the migration job to run successfully.
I have tested this change locally and it seems to be working as expected. I hope this fix will be helpful to others who are experiencing the same issue.
Thank you for your time and consideration.
> Remove the line from  .en.shared file

- packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.component.tsx
- packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.storage.ts
- packages/webapp-libs/webapp-tenants/src/providers/currentTenantProvider/currentTenantProvider.types.ts
Fix issue with showing invalid active tenant loaded from localStorage that was assigned in other user session
Currently there is only single tenant id stored in localStorage that keeps the information about last active tenant. Lack of logged user information in this state cause the issue that loads wrong tenant as current tenant where it's missing in the URL.
Instead of saving only tenant it, the map of `user id => tenant id` is saved so there is no issue between login sessions.
Should not. If there will be any error, clearing localStorage data should help.
> fix: Fix issue with showing invalid active tenant in selector

- packages/backend/apps/multitenancy/schema.py
It removes duplicated type for TenantMembershipRole in graphql schema.
There are two different types for same enum
> fix: multi tenancy enum duplicate schema

- packages/webapp-libs/webapp-finances/src/routes/editPaymentMethod/editPaymentMethod.component.tsx
- packages/webapp-libs/webapp-finances/src/routes/subscriptions/currentSubscription.component.tsx
- packages/webapp-libs/webapp-tenants/src/components/tenantRoleAccess/__tests__/tenantRoleAccess.component.spec.tsx
- packages/webapp-libs/webapp-tenants/src/components/tenantRoleAccess/index.ts
- packages/webapp-libs/webapp-tenants/src/components/tenantRoleAccess/tenantRoleAccess.component.tsx
- packages/webapp-libs/webapp-tenants/src/routes/tenantSettings/tenantSettings.component.tsx
- packages/webapp/src/app/app.component.tsx
- packages/webapp/src/shared/components/layout/sidebar/sidebar.component.tsx
- packages/webapp/src/shared/components/roleAccess/__tests__/roleAccess.component.spec.tsx
Add TenantRoleAccess component, fix subscriptions routing, add Subscription tab to tenant settings page
> feat: Multi tenancy subscriptions routing

- .versionrc.js
Add `deps:` type to conventional-changelog configuration so the dependencies updates will be visible in the generated changelog.
> feat: Add `deps:` type to conventional-changelog

- packages/backend/apps/multitenancy/schema.py
- packages/backend/apps/multitenancy/tests/test_schema.py
Additional checking and actions for tenant removal mutation.
All tenants can be removed.
Blocking tenant delete of type `default` and add subscription cancellation during tenant removal.
Nope
> feat: multi tenancy delete tenant validation

- packages/internal/cli/package.json
- packages/internal/cli/src/lib/awsVault.ts
- packages/internal/cli/src/lib/chamber.ts
- packages/internal/cli/src/lib/docker.ts
- packages/webapp/.storybook/main.ts
- packages/webapp/.storybook/preview.ts
- packages/webapp/package.json
- pnpm-lock.yaml
Update deprecated deps: `@ocllif/errors` and `@storybook/addon-styling`. Recommended libraries were used instead. 
There is only one deprecated dep left: `subscriptions-transport-ws`, which seems to be added on purpose for custom graphql ws link implementation. I've decided to leave that one alone.
> deps: deprecated packages

- packages/backend/apps/finances/serializers.py
- packages/backend/apps/finances/services/subscriptions.py
- packages/backend/common/tasks.py
It switches from `pytz` package to `django.datetime.timezone` because of security reasons.
> fix: Switch from pytz to datetime.timezone package

- packages/webapp-libs/webapp-contentful/tsconfig.spec.json
- packages/webapp-libs/webapp-core/tsconfig.json
- packages/webapp-libs/webapp-core/tsconfig.spec.json
- packages/webapp-libs/webapp-emails/tsconfig.spec.json
`...*.spec.tsx` was missing from `include` array in `tsconfig.spec.json` files across multiple internal packages. That led to many ts errors shown by language server inside editors with missing type declarations etc.
> fix: Missing *.spec.tsx pattern in multiple tsconfig.spec.json files

- packages/backend/apps/multitenancy/pipeline.py
- packages/backend/apps/multitenancy/tests/test_pipeline.py
- packages/backend/config/settings.py
Creating default tenant for users who register using social apps.
Default tenant is not created which trigger error on FE.
> fix: Create default tenant for newly created social users

- packages/webapp-libs/webapp-api-client/src/api/auth/auth.hooks.ts
- packages/webapp/src/shared/components/auth/loginForm/__tests__/loginForm.component.spec.tsx
- packages/webapp/src/shared/components/auth/loginForm/loginForm.hooks.ts
- packages/webapp/src/shared/components/auth/validateOtpForm/__tests__/validateOtpForm.component.spec.tsx
- packages/webapp/src/shared/components/auth/validateOtpForm/validateOtpForm.component.tsx
- packages/webapp/src/shared/components/routes/anonymousRoute/__tests__/anonymousRoute.component.spec.tsx
- packages/webapp/src/shared/components/routes/anonymousRoute/anonymousRoute.component.tsx
- packages/webapp/src/shared/components/routes/authRoute/authRoute.component.tsx
- packages/webapp/src/shared/components/routes/authRoute/authRoute.hook.tsx
Add redirection to previous page after login
[Add support for returnUrl to the webapp](https://github.com/apptension/saas-boilerplate/issues/519)
The user is redirected based on the entered path. 
Tech note: The relative path is required, as the absolute path generates too many re-renders and the user is redirected to the home page due to an empty searchParam after the first redirection based on searchParam.
> feat: add redirection to previous page after login

- packages/internal/cli/src/config/env.ts
- packages/internal/cli/src/config/telemetry.ts
Closes #587 
Fixes CLI telemetry opt-out not working as expected.
> fix: #587 Fix CLI telemetry opt-out

- .github/workflows/actions/setup/action.yml
- bitbucket-pipelines.yml
- packages/infra/infra-core/package.json
- packages/infra/infra-core/src/lib/patterns/serviceCiConfig.ts
- packages/internal/docs/package.json
- packages/workers/Dockerfile
- pnpm-lock.yaml
New version of pnpm (9.5.0) fixes filtering, which breaks CI builds.
pnpm is locked on CI to ~9.5.0 and filtering of the `backend` package is fixed by adding `...`
> fix: Fix broken builds on pnpm ^9.5.0

- packages/internal/docs/docs/api-reference/env-files.mdx
- packages/internal/docs/docs/aws/deploy-to-aws/create-env-stage-in-repo.mdx
Fixes #603
Documentation of the `SB_DOMAIN_FLOWER` is missing.
> docs: #603 Add missing SB_DOMAIN_FLOWER env documentation

- packages/backend/infra/stacks/lib/backendTaskRole.ts
- packages/backend/infra/stacks/lib/environment.ts
Fixes #604 
Added `AWS_EXPORTS_STORAGE_BUCKET_NAME` env and allow backend task role to access exports bucket.
Export functionality fill fail because there is no `AWS_EXPORTS_STORAGE_BUCKET_NAME` set.
> fix: #604 Fix user export

- packages/infra/infra-shared/src/stacks/main/mainRedisCluster.ts
Updated to use subnetGroup.ref in cacheSubnetGroupName to allow CDK to infer the dependency.
- [ X ] The commit message follows our guidelines
Bug fix
Causes error in deployment when running pnpm saas infra deploy 
https://github.com/apptension/saas-boilerplate/issues/621
Now deploys without error
No
> fix : #621 Redis cache deployment issue

- packages/webapp-libs/webapp-tenants/src/components/tenantSwitch/tenantSwitch.component.tsx
Use ellipses for long organization names for a current tenant name in tenant switch.
> fix: #599 Use ellipses for long organization names

- packages/webapp-libs/webapp-core/src/config/env.ts
- 
Set default value for VITE_EMAIL_ASSETS_URL env. Without it emails in storybooks doesn't link to the correct assets location (assets are missing).
> fix: Set default value for VITE_EMAIL_ASSETS_URL env

- packages/backend/apps/notifications/schema.py
Bug fix
After adding profile picture notification broadcasting stops working.
After adding avatar relation to prefetch_related avatar is prefetched and bug is no longer exists. Notifications are sent correctly.
Nope
> fix: #628 Add selecting avatar to queryset

- package.json
- pnpm-lock.yaml
Bug fix
On a new install of packages, there is a possibility to install a different version of `react-router-dom` and `react-router` which causes an error that indicates that `useNaviagte` is used outside of the Route component.
In new versions, those libraries are matched and locked to prevent such errors.
> fix: #653 Lock and match versions of react-router libraries

- .lintstagedrc
- .prettierignore
bug fix
Linter is correcting backend django admin templates which breaks them.
Ignoring django templates directory
No
> fix: #642 Ignore whole backend/templates directory on precommit linter

- packages/backend/config/monitoring.py
When using Sentry to log all errors, the InvalidToken error which is thrown very often when access token needs to be refreshed eats most the available quota.
It mutes the error so it's ignored by the Sentry.
> fix: Mute InvalidToken error in Sentry
